### PR TITLE
fix(pointcut): do not apply the same advice twice

### LINKED ISSUE #40: Sequencing of the decorators calls (multiple advices calling)
## Problem
```javascript
@Wove()
class Example {
    foo() {
        console.log('within foo');
    }
    bar() {
        console.log('within bar');
    }
}

const example = new Example();

setTimeout(() => {
    example.foo();
    example.bar();
}, 1e3);

class Aspect {
    @beforeMethod({ classNamePattern: /^(Example)$/, methodNamePattern: /^foo/})
    beforeFoo() {
        console.log('before foo');
    }

    @afterMethod({ classNamePattern: /^(Example)$/, methodNamePattern: /^bar/})
    afterBar() {
        console.log('before bar');
    }
}
```
In such code `beforeFoo()` advice will be executed twice, despite `foo()` is called once.
It is because of the sequencing of the decorators functions calls (`@Wove, @beforeMethod, @afterMethod`). If move `Example` class declaration after `Aspect` class, it will be no problem (`@Wove` decorator will be executed after `@beforeMethod and @afterMethod`).
## Possible Solution
As a fast variant it could be solved by returning from `woveTarget()` func of the joint_points classes if jointpoint was already `__woven__`. For method_call jointpoint:
```javascript
protected woveTarget(proto: any, key:string, advice: Advice, woveMetadata: any) {
    // Add this:
    if (proto[key].__woven__) {
        return;
    }

    let className = proto.constructor.name;
    let bak = proto[key];
    let self = this;
    proto[key] = function () {
      let metadata = self.getMetadata(className, key, bak, arguments, this, woveMetadata);
      return advice.wove(bak, metadata);
    };
    proto[key].__woven__ = true;
}
```

### PR DESCRIPTION
**Pull request by mgechev**
Fix #40

### CODE REVIEW

File: lib/src/core/pointcut.ts [hunk 1]
```diff
@@ -6,7 +6,14 @@ export class Pointcut {
 
   public advice: Advice;
 
+  private _applications = new Set<Function>();
+
   public apply(fn: Function, woveMetadata: any) {
+    if (this._applications.has(fn)) {
+      return;
+    } else {
```
Comment (SamVerschueren) [inline lib/src/core/pointcut.ts]: You could remove the else because you return in the if. Depends on code style :).
